-- Config: permite enviar facturas normales a la cola de fraccionamiento
IF NOT EXISTS (
  SELECT 1 FROM dbo.SETTINGS WHERE OPCION = N'PERMITE FRACCIONAMIENTO FACTURAS'
)
BEGIN
  INSERT INTO dbo.SETTINGS (OPCION, VALOR)
  VALUES (N'PERMITE FRACCIONAMIENTO FACTURAS', N'SI');
END;
GO
