-- Vales a empleados (acreditación por vale de caja o banco; no van al corte)
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NOMINA_VALES_EMPLEADOS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  CREATE TABLE dbo.NOMINA_VALES_EMPLEADOS (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    EMPNIT VARCHAR(20) NOT NULL,
    CODEMP INT NOT NULL,
    CODCAJA INT NULL,
    FECHA DATE NOT NULL,
    MES INT NOT NULL,
    ANIO INT NOT NULL,
    MONTO DECIMAL(18, 3) NOT NULL,
    ABONOS DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_VALES_ABONOS0 DEFAULT (0),
    SALDO DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_VALES_SALDO0 DEFAULT (0),
    CUOTAS INT NOT NULL CONSTRAINT DF_NOMINA_VALES_CUOTAS0 DEFAULT (1),
    DESCRIPCION VARCHAR(250) NULL,
    USUARIO VARCHAR(50) NULL,
    FECHA_CREACION DATETIME NOT NULL CONSTRAINT DF_NOMINA_VALES_FC DEFAULT (GETDATE()),
    CORTE VARCHAR(2) NOT NULL CONSTRAINT DF_NOMINA_VALES_CORTE DEFAULT ('NO'),
    NOCORTE INT NULL,
    GENERADO_TIPO VARCHAR(10) NULL,
    GENERADO_CODIGO INT NULL,
    GENERADO_CODDOC VARCHAR(50) NULL,
    GENERADO_CORRELATIVO DECIMAL(18, 0) NULL,
    CONSTRAINT CK_NOMINA_VALES_CORTE CHECK (CORTE IN ('SI', 'NO')),
    CONSTRAINT CK_NOMINA_VALES_MONTO CHECK (MONTO > 0)
  );
  CREATE INDEX IX_NOMINA_VALES_EMP_MES ON dbo.NOMINA_VALES_EMPLEADOS (EMPNIT, ANIO, MES);
  CREATE INDEX IX_NOMINA_VALES_CAJA_CORTE ON dbo.NOMINA_VALES_EMPLEADOS (EMPNIT, CODCAJA, CORTE, FECHA_CREACION);
END;
GO

-- Columnas de corte / abonos / saldo por si la tabla ya existía sin ellas
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NOMINA_VALES_EMPLEADOS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  IF COL_LENGTH('dbo.NOMINA_VALES_EMPLEADOS', 'CORTE') IS NULL
    ALTER TABLE dbo.NOMINA_VALES_EMPLEADOS ADD CORTE VARCHAR(2) NOT NULL CONSTRAINT DF_NOMINA_VALES_CORTE2 DEFAULT ('NO');
  IF COL_LENGTH('dbo.NOMINA_VALES_EMPLEADOS', 'NOCORTE') IS NULL
    ALTER TABLE dbo.NOMINA_VALES_EMPLEADOS ADD NOCORTE INT NULL;
  IF COL_LENGTH('dbo.NOMINA_VALES_EMPLEADOS', 'FECHA_CREACION') IS NULL
    ALTER TABLE dbo.NOMINA_VALES_EMPLEADOS ADD FECHA_CREACION DATETIME NOT NULL CONSTRAINT DF_NOMINA_VALES_FC2 DEFAULT (GETDATE());
  IF COL_LENGTH('dbo.NOMINA_VALES_EMPLEADOS', 'ABONOS') IS NULL
    ALTER TABLE dbo.NOMINA_VALES_EMPLEADOS ADD ABONOS DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_VALES_ABONOS DEFAULT (0);
  IF COL_LENGTH('dbo.NOMINA_VALES_EMPLEADOS', 'SALDO') IS NULL
    ALTER TABLE dbo.NOMINA_VALES_EMPLEADOS ADD SALDO DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_VALES_SALDO DEFAULT (0);
  IF COL_LENGTH('dbo.NOMINA_VALES_EMPLEADOS', 'CUOTAS') IS NULL
    ALTER TABLE dbo.NOMINA_VALES_EMPLEADOS ADD CUOTAS INT NOT NULL CONSTRAINT DF_NOMINA_VALES_CUOTAS DEFAULT (1);
  -- Forma de acreditación + documento generado (vale caja o salida banco)
  IF COL_LENGTH('dbo.NOMINA_VALES_EMPLEADOS', 'GENERADO_TIPO') IS NULL
    ALTER TABLE dbo.NOMINA_VALES_EMPLEADOS ADD GENERADO_TIPO VARCHAR(10) NULL;
  IF COL_LENGTH('dbo.NOMINA_VALES_EMPLEADOS', 'GENERADO_CODIGO') IS NULL
    ALTER TABLE dbo.NOMINA_VALES_EMPLEADOS ADD GENERADO_CODIGO INT NULL;
  IF COL_LENGTH('dbo.NOMINA_VALES_EMPLEADOS', 'GENERADO_CODDOC') IS NULL
    ALTER TABLE dbo.NOMINA_VALES_EMPLEADOS ADD GENERADO_CODDOC VARCHAR(50) NULL;
  IF COL_LENGTH('dbo.NOMINA_VALES_EMPLEADOS', 'GENERADO_CORRELATIVO') IS NULL
    ALTER TABLE dbo.NOMINA_VALES_EMPLEADOS ADD GENERADO_CORRELATIVO DECIMAL(18, 0) NULL;
  -- CODCAJA queda opcional: la acreditación vive en GENERADO_*
  IF EXISTS (
    SELECT 1
    FROM sys.columns
    WHERE object_id = OBJECT_ID('dbo.NOMINA_VALES_EMPLEADOS')
      AND name = 'CODCAJA'
      AND is_nullable = 0
  )
    ALTER TABLE dbo.NOMINA_VALES_EMPLEADOS ALTER COLUMN CODCAJA INT NULL;
  -- Backfill: saldo = monto - abonos
  UPDATE dbo.NOMINA_VALES_EMPLEADOS
  SET ABONOS = ISNULL(ABONOS, 0),
      SALDO = CASE
        WHEN ISNULL(SALDO, 0) = 0 AND ISNULL(ABONOS, 0) = 0 THEN MONTO
        ELSE ROUND(MONTO - ISNULL(ABONOS, 0), 3)
      END
  WHERE ISNULL(SALDO, 0) = 0 AND ISNULL(ABONOS, 0) = 0;
END;
GO

-- Pagos / abonos a vales de empleados
-- Esquema: ID, IDVALE, EMPNIT, CODCAJA, FECHA_PAGO, ABONO, CORTE, NOCORTE
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NOMINA_VALES_EMPLEADOS_PAGOS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  CREATE TABLE dbo.NOMINA_VALES_EMPLEADOS_PAGOS (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    IDVALE INT NULL,
    EMPNIT VARCHAR(50) NULL,
    CODCAJA INT NULL,
    FECHA_PAGO DATE NULL,
    ABONO DECIMAL(18, 3) NULL,
    CORTE VARCHAR(2) NULL,
    NOCORTE INT NULL
  );
  CREATE INDEX IX_NOMINA_VALES_PAGOS_VALE ON dbo.NOMINA_VALES_EMPLEADOS_PAGOS (IDVALE, FECHA_PAGO);
  CREATE INDEX IX_NOMINA_VALES_PAGOS_CAJA ON dbo.NOMINA_VALES_EMPLEADOS_PAGOS (EMPNIT, CODCAJA, CORTE);
END;
GO

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NOMINA_VALES_EMPLEADOS_PAGOS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  IF COL_LENGTH('dbo.NOMINA_VALES_EMPLEADOS_PAGOS', 'CODCAJA') IS NULL
    ALTER TABLE dbo.NOMINA_VALES_EMPLEADOS_PAGOS ADD CODCAJA INT NULL;
  IF COL_LENGTH('dbo.NOMINA_VALES_EMPLEADOS_PAGOS', 'CORTE') IS NULL
    ALTER TABLE dbo.NOMINA_VALES_EMPLEADOS_PAGOS ADD CORTE VARCHAR(2) NULL;
  IF COL_LENGTH('dbo.NOMINA_VALES_EMPLEADOS_PAGOS', 'NOCORTE') IS NULL
    ALTER TABLE dbo.NOMINA_VALES_EMPLEADOS_PAGOS ADD NOCORTE INT NULL;
END;
GO

-- Passkey / WebAuthn en empleados (JSON con credenciales del dispositivo)
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'Empleados' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  IF COL_LENGTH('dbo.Empleados', 'PASSKEY') IS NULL
    ALTER TABLE dbo.Empleados ADD PASSKEY NVARCHAR(MAX) NULL;
END;
GO
