-- Campañas de promociones y registros asociados.
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PROMOCIONES' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  CREATE TABLE dbo.PROMOCIONES (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    EMPNIT VARCHAR(50) NOT NULL,
    NOMBRE VARCHAR(MAX) NOT NULL,
    FECHA_INICIO DATE NULL,
    FECHA_FIN DATE NULL,
    STATUS VARCHAR(20) NOT NULL CONSTRAINT DF_PROMOCIONES_STATUS DEFAULT ('ACTIVA'),
    CONSTRAINT CK_PROMOCIONES_STATUS CHECK (STATUS IN ('ACTIVA', 'FINALIZADA'))
  );
  CREATE INDEX IX_PROMOCIONES_EMP_STATUS ON dbo.PROMOCIONES (EMPNIT, STATUS);
  CREATE INDEX IX_PROMOCIONES_EMP_FECHA ON dbo.PROMOCIONES (EMPNIT, FECHA_INICIO, FECHA_FIN);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PROMOCIONES_REGISTROS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  CREATE TABLE dbo.PROMOCIONES_REGISTROS (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    IDPROMO INT NOT NULL,
    FECHA DATE NULL,
    CODIGO INT NULL,
    TIPO VARCHAR(50) NULL,
    VALOR VARCHAR(200) NULL,
    CONSTRAINT FK_PROMOCIONES_REGISTROS_PROMO
      FOREIGN KEY (IDPROMO) REFERENCES dbo.PROMOCIONES (ID) ON DELETE CASCADE
  );
  CREATE INDEX IX_PROMOCIONES_REGISTROS_PROMO ON dbo.PROMOCIONES_REGISTROS (IDPROMO, FECHA);
END;
GO
