-- Esquema compartido Los ERP: DTE SV + receptor clientes + mín/máx inventario.
-- Idempotente (COL_LENGTH / IF NOT EXISTS). VERSION updater: 2026 / DB: P.

-- @UPDATER_CHUNK fel-credenciales-table
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'FEL_CREDENCIALES' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  CREATE TABLE dbo.FEL_CREDENCIALES (
    EMPNIT VARCHAR(50) NOT NULL PRIMARY KEY,
    CERTIFICACION_USUARIO VARCHAR(100) NULL,
    CERTIFICACION_LLAVE VARCHAR(200) NULL,
    FIRMA_ALIAS VARCHAR(100) NULL,
    FIRMA_LLAVE VARCHAR(200) NULL,
    EMISOR_NIT VARCHAR(30) NULL,
    EMISOR_NOMBRE NVARCHAR(250) NULL,
    EMISOR_NOMBRECOMECIAL NVARCHAR(250) NULL,
    EMISOR_DIRECCION NVARCHAR(300) NULL,
    EMISOR_DEPARTAMENTO VARCHAR(50) NULL,
    EMISOR_MUNICIPIO VARCHAR(50) NULL,
    EMISOR_CODIGOPOSTAL VARCHAR(20) NULL,
    EMISOR_CODIGOESTABLECIMIENTO VARCHAR(20) NULL,
    EMISOR_FRASE INT NULL,
    EMISOR_ESCENARIO INT NULL,
    EMISOR_FRASE2 INT NULL,
    EMISOR_ESCENARIO2 INT NULL,
    NIT_RESOLUCION VARCHAR(50) NULL,
    NIT_FECHA_RESOLUCION VARCHAR(50) NULL,
    ADENDA_SUCURSAL NVARCHAR(100) NULL,
    ADENDA_TELSUCURSAL VARCHAR(50) NULL,
    ADENDA_TELSUPERVISOR VARCHAR(50) NULL,
    VENCE_CERTIFICADO DATE NULL
  );
END;

-- @UPDATER_CHUNK fel-credenciales-dte-cols
IF COL_LENGTH('dbo.FEL_CREDENCIALES', 'AMBIENTE') IS NULL
  ALTER TABLE dbo.FEL_CREDENCIALES ADD AMBIENTE VARCHAR(2) NULL;
IF COL_LENGTH('dbo.FEL_CREDENCIALES', 'MODO_SIMULACION') IS NULL
  ALTER TABLE dbo.FEL_CREDENCIALES ADD MODO_SIMULACION VARCHAR(2) NULL;
IF COL_LENGTH('dbo.FEL_CREDENCIALES', 'URL_AUTH') IS NULL
  ALTER TABLE dbo.FEL_CREDENCIALES ADD URL_AUTH VARCHAR(300) NULL;
IF COL_LENGTH('dbo.FEL_CREDENCIALES', 'URL_FIRMADOR') IS NULL
  ALTER TABLE dbo.FEL_CREDENCIALES ADD URL_FIRMADOR VARCHAR(300) NULL;
IF COL_LENGTH('dbo.FEL_CREDENCIALES', 'URL_RECEPCION') IS NULL
  ALTER TABLE dbo.FEL_CREDENCIALES ADD URL_RECEPCION VARCHAR(300) NULL;
IF COL_LENGTH('dbo.FEL_CREDENCIALES', 'URL_CONSULTA') IS NULL
  ALTER TABLE dbo.FEL_CREDENCIALES ADD URL_CONSULTA VARCHAR(300) NULL;
IF COL_LENGTH('dbo.FEL_CREDENCIALES', 'EMISOR_NRC') IS NULL
  ALTER TABLE dbo.FEL_CREDENCIALES ADD EMISOR_NRC VARCHAR(20) NULL;
IF COL_LENGTH('dbo.FEL_CREDENCIALES', 'EMISOR_CODACTIVIDAD') IS NULL
  ALTER TABLE dbo.FEL_CREDENCIALES ADD EMISOR_CODACTIVIDAD VARCHAR(10) NULL;
IF COL_LENGTH('dbo.FEL_CREDENCIALES', 'EMISOR_DESCACTIVIDAD') IS NULL
  ALTER TABLE dbo.FEL_CREDENCIALES ADD EMISOR_DESCACTIVIDAD NVARCHAR(150) NULL;
IF COL_LENGTH('dbo.FEL_CREDENCIALES', 'EMISOR_TELEFONO') IS NULL
  ALTER TABLE dbo.FEL_CREDENCIALES ADD EMISOR_TELEFONO VARCHAR(30) NULL;
IF COL_LENGTH('dbo.FEL_CREDENCIALES', 'EMISOR_CORREO') IS NULL
  ALTER TABLE dbo.FEL_CREDENCIALES ADD EMISOR_CORREO VARCHAR(100) NULL;
IF COL_LENGTH('dbo.FEL_CREDENCIALES', 'EMISOR_TIPOESTABLECIMIENTO') IS NULL
  ALTER TABLE dbo.FEL_CREDENCIALES ADD EMISOR_TIPOESTABLECIMIENTO VARCHAR(5) NULL;
IF COL_LENGTH('dbo.FEL_CREDENCIALES', 'EMISOR_CODIGOPUNTOVENTA') IS NULL
  ALTER TABLE dbo.FEL_CREDENCIALES ADD EMISOR_CODIGOPUNTOVENTA VARCHAR(20) NULL;

-- @UPDATER_CHUNK clientes-dte-cols
IF COL_LENGTH('dbo.CLIENTES', 'NRC') IS NULL
  ALTER TABLE dbo.CLIENTES ADD NRC VARCHAR(20) NULL;
IF COL_LENGTH('dbo.CLIENTES', 'TIPODOCUMENTO_DTE') IS NULL
  ALTER TABLE dbo.CLIENTES ADD TIPODOCUMENTO_DTE VARCHAR(5) NULL;
IF COL_LENGTH('dbo.CLIENTES', 'NUMDOCUMENTO_DTE') IS NULL
  ALTER TABLE dbo.CLIENTES ADD NUMDOCUMENTO_DTE VARCHAR(36) NULL;
IF COL_LENGTH('dbo.CLIENTES', 'COD_ACTIVIDAD') IS NULL
  ALTER TABLE dbo.CLIENTES ADD COD_ACTIVIDAD VARCHAR(10) NULL;
IF COL_LENGTH('dbo.CLIENTES', 'DESC_ACTIVIDAD') IS NULL
  ALTER TABLE dbo.CLIENTES ADD DESC_ACTIVIDAD NVARCHAR(150) NULL;
IF COL_LENGTH('dbo.CLIENTES', 'REGIMEN_DTE') IS NULL
  ALTER TABLE dbo.CLIENTES ADD REGIMEN_DTE VARCHAR(10) NULL;
IF COL_LENGTH('dbo.CLIENTES', 'TIPO_CONTRIBUYENTE') IS NULL
  ALTER TABLE dbo.CLIENTES ADD TIPO_CONTRIBUYENTE VARCHAR(20) NULL;
IF COL_LENGTH('dbo.CLIENTES', 'DEPARTAMENTO_MH') IS NULL
  ALTER TABLE dbo.CLIENTES ADD DEPARTAMENTO_MH VARCHAR(5) NULL;
IF COL_LENGTH('dbo.CLIENTES', 'MUNICIPIO_MH') IS NULL
  ALTER TABLE dbo.CLIENTES ADD MUNICIPIO_MH VARCHAR(5) NULL;
IF COL_LENGTH('dbo.CLIENTES', 'DISTRITO_MH') IS NULL
  ALTER TABLE dbo.CLIENTES ADD DISTRITO_MH VARCHAR(5) NULL;

-- @UPDATER_CHUNK productos-inv-min-max
IF COL_LENGTH('dbo.PRODUCTOS', 'INVMINIMO') IS NULL
  ALTER TABLE dbo.PRODUCTOS ADD INVMINIMO DECIMAL(18, 4) NULL;
IF COL_LENGTH('dbo.PRODUCTOS', 'INVMAXIMO') IS NULL
  ALTER TABLE dbo.PRODUCTOS ADD INVMAXIMO DECIMAL(18, 4) NULL;
