-- @UPDATER_ID nomina-detalle-deducciones
-- Deducciones desglosadas por línea de planilla (vales, manual, etc.)
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NOMINA_DETALLE_DEDUCCIONES' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  CREATE TABLE dbo.NOMINA_DETALLE_DEDUCCIONES (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    DETALLE_ID INT NOT NULL,
    EMPNIT VARCHAR(20) NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    REF_ID INT NULL,
    PAGO_VALE_ID INT NULL,
    DESCRIPCION VARCHAR(250) NULL,
    MONTO DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_DED_MONTO DEFAULT (0),
    FECHA_CREACION DATETIME NOT NULL CONSTRAINT DF_NOMINA_DET_DED_FC DEFAULT (GETDATE()),
    CONSTRAINT CK_NOMINA_DET_DED_TIPO CHECK (TIPO IN ('VALE', 'MANUAL'))
  );
  CREATE INDEX IX_NOMINA_DET_DED_DET ON dbo.NOMINA_DETALLE_DEDUCCIONES (DETALLE_ID);
  CREATE INDEX IX_NOMINA_DET_DED_EMP ON dbo.NOMINA_DETALLE_DEDUCCIONES (EMPNIT, DETALLE_ID);
END;
GO
