-- =============================================================================
-- MÓDULO NÓMINAS — OnneB PLUS
-- Ejecutar vía Actualizador BD (UPDATE_QUERIES) o directamente en SQL Server.
-- Actualizador: npm run seed:updater:nomina (3 lotes @UPDATER_CHUNK en este archivo).
-- Empleados activos: dbo.Empleados.ACTIVO = 'SI' (equivalente operativo a HABILITADO).
-- =============================================================================

-- @UPDATER_CHUNK NOMINA_TABLAS
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NOMINA_CONFIG' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  CREATE TABLE dbo.NOMINA_CONFIG (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    EMPNIT VARCHAR(20) NOT NULL,
    NIT_PATRONO VARCHAR(25) NULL,
    RAZON_SOCIAL VARCHAR(200) NULL,
    IGSS_NUMERO_PATRONO VARCHAR(20) NULL,
    IGSS_CENTRO_TRABAJO VARCHAR(10) NULL CONSTRAINT DF_NOMINA_CONFIG_CENTRO DEFAULT ('1'),
    IGSS_EMAIL VARCHAR(120) NULL,
    PORC_IGSS_LABORAL DECIMAL(8, 4) NOT NULL CONSTRAINT DF_NOMINA_CONFIG_IGSS_LAB DEFAULT (4.83),
    PORC_IGSS_PATRONAL DECIMAL(8, 4) NOT NULL CONSTRAINT DF_NOMINA_CONFIG_IGSS_PAT DEFAULT (10.67),
    PORC_ISR DECIMAL(8, 4) NOT NULL CONSTRAINT DF_NOMINA_CONFIG_ISR DEFAULT (0),
    DIAS_MES DECIMAL(8, 2) NOT NULL CONSTRAINT DF_NOMINA_CONFIG_DIAS DEFAULT (30),
    SALARIO_MINIMO DECIMAL(18, 3) NULL,
    OBS VARCHAR(500) NULL,
    CONSTRAINT UQ_NOMINA_CONFIG_EMP UNIQUE (EMPNIT)
  );
  CREATE INDEX IX_NOMINA_CONFIG_EMP ON dbo.NOMINA_CONFIG (EMPNIT);
END;

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NOMINA_CONCEPTOS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  CREATE TABLE dbo.NOMINA_CONCEPTOS (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    EMPNIT VARCHAR(20) NOT NULL,
    CODIGO VARCHAR(20) NOT NULL,
    DESCRIPCION VARCHAR(120) NOT NULL,
    TIPO VARCHAR(3) NOT NULL CONSTRAINT DF_NOMINA_CONCEPTOS_TIPO DEFAULT ('ING'),
    AFECTA_IGSS VARCHAR(2) NOT NULL CONSTRAINT DF_NOMINA_CONCEPTOS_IGSS DEFAULT ('SI'),
    AFECTA_ISR VARCHAR(2) NOT NULL CONSTRAINT DF_NOMINA_CONCEPTOS_ISR DEFAULT ('SI'),
    ACTIVO VARCHAR(2) NOT NULL CONSTRAINT DF_NOMINA_CONCEPTOS_ACT DEFAULT ('SI'),
    CONSTRAINT UQ_NOMINA_CONCEPTOS_COD UNIQUE (EMPNIT, CODIGO),
    CONSTRAINT CK_NOMINA_CONCEPTOS_TIPO CHECK (TIPO IN ('ING', 'DED'))
  );
  CREATE INDEX IX_NOMINA_CONCEPTOS_EMP ON dbo.NOMINA_CONCEPTOS (EMPNIT);
END;

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NOMINA_DEPARTAMENTOS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  CREATE TABLE dbo.NOMINA_DEPARTAMENTOS (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    EMPNIT VARCHAR(20) NOT NULL,
    CODIGO VARCHAR(20) NOT NULL,
    NOMBRE VARCHAR(120) NOT NULL,
    ACTIVO VARCHAR(2) NOT NULL CONSTRAINT DF_NOMINA_DEP_ACT DEFAULT ('SI'),
    CONSTRAINT UQ_NOMINA_DEPARTAMENTOS UNIQUE (EMPNIT, CODIGO),
    CONSTRAINT CK_NOMINA_DEP_ACTIVO CHECK (ACTIVO IN ('SI', 'NO'))
  );
  CREATE INDEX IX_NOMINA_DEPARTAMENTOS_EMP ON dbo.NOMINA_DEPARTAMENTOS (EMPNIT, ACTIVO);
END;

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NOMINA_EMPLEADO' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  CREATE TABLE dbo.NOMINA_EMPLEADO (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    EMPNIT VARCHAR(20) NOT NULL,
    CODEMPLEADO INT NOT NULL,
    SALARIO_BASE DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_EMP_SAL DEFAULT (0),
    FECHA_INGRESO DATE NULL,
    FECHA_BAJA DATE NULL,
    COD_CENTRO_TRABAJO VARCHAR(10) NULL,
    CONDICION_LABORAL VARCHAR(1) NOT NULL CONSTRAINT DF_NOMINA_EMP_COND DEFAULT ('P'),
    TIPO_SALARIO_IGSS VARCHAR(2) NULL,
    TIEMPO_COMPLETO VARCHAR(2) NOT NULL CONSTRAINT DF_NOMINA_EMP_TC DEFAULT ('SI'),
    HORAS_MES DECIMAL(8, 2) NULL,
    COD_OCUPACION_IGSS VARCHAR(10) NULL,
    CUENTA_BANCO VARCHAR(40) NULL,
    DEPARTAMENTO VARCHAR(120) NULL,
    BONO_LEY DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_EMP_BONO_LEY DEFAULT (0),
    BONO_ADICIONAL DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_EMP_BONO_ADI DEFAULT (0),
    OBS VARCHAR(250) NULL,
    CONSTRAINT UQ_NOMINA_EMPLEADO UNIQUE (EMPNIT, CODEMPLEADO),
    CONSTRAINT CK_NOMINA_EMP_COND CHECK (CONDICION_LABORAL IN ('P', 'T'))
  );
  CREATE INDEX IX_NOMINA_EMPLEADO_EMP ON dbo.NOMINA_EMPLEADO (EMPNIT, CODEMPLEADO);
END;

-- @UPDATER_CHUNK NOMINA_PLANILLAS
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NOMINA_PLANILLAS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  CREATE TABLE dbo.NOMINA_PLANILLAS (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    EMPNIT VARCHAR(20) NOT NULL,
    TIPO VARCHAR(10) NOT NULL,
    PERIODO_TIPO VARCHAR(15) NOT NULL CONSTRAINT DF_NOMINA_PLAN_PER DEFAULT ('MENSUAL'),
    MES INT NOT NULL,
    ANIO INT NOT NULL,
    FECHA_INICIO DATE NULL,
    FECHA_FIN DATE NULL,
    FECHA_PAGO DATE NULL,
    DESCRIPCION VARCHAR(200) NULL,
    STATUS VARCHAR(1) NOT NULL CONSTRAINT DF_NOMINA_PLAN_ST DEFAULT ('B'),
    USUARIO VARCHAR(50) NULL,
    FECHA_CREACION DATETIME NOT NULL CONSTRAINT DF_NOMINA_PLAN_FC DEFAULT (GETDATE()),
    TOTAL_INGRESOS DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_PLAN_TING DEFAULT (0),
    TOTAL_DEDUCCIONES DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_PLAN_TDED DEFAULT (0),
    TOTAL_NETO DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_PLAN_TNET DEFAULT (0),
    TOTAL_IGSS_LAB DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_PLAN_TIGL DEFAULT (0),
    TOTAL_IGSS_PAT DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_PLAN_TIGP DEFAULT (0),
    OBS VARCHAR(500) NULL,
    CONSTRAINT CK_NOMINA_PLAN_TIPO CHECK (TIPO IN ('INTERNA', 'IGSS')),
    CONSTRAINT CK_NOMINA_PLAN_STATUS CHECK (STATUS IN ('B', 'C', 'F', 'A'))
  );
  CREATE INDEX IX_NOMINA_PLANILLAS_EMP ON dbo.NOMINA_PLANILLAS (EMPNIT, ANIO, MES, TIPO);
END;

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NOMINA_DETALLE' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  CREATE TABLE dbo.NOMINA_DETALLE (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    PLANILLA_ID INT NOT NULL,
    EMPNIT VARCHAR(20) NOT NULL,
    CODEMPLEADO INT NOT NULL,
    NOMEMPLEADO VARCHAR(120) NULL,
    DPI VARCHAR(20) NULL,
    IGSS VARCHAR(20) NULL,
    SALARIO_BASE DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_SAL DEFAULT (0),
    DIAS_LABORADOS DECIMAL(8, 2) NOT NULL CONSTRAINT DF_NOMINA_DET_DIAS DEFAULT (30),
    HORAS_LABORADAS DECIMAL(8, 2) NULL,
    OTROS_INGRESOS DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_OING DEFAULT (0),
    BONIFICACION DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_BON DEFAULT (0),
    BONO_LEY DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_BONO_LEY DEFAULT (0),
    BONO_ADICIONAL DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_BONO_ADI DEFAULT (0),
    COMISION DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_COM DEFAULT (0),
    IGSS_LABORAL DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_IGL DEFAULT (0),
    IGSS_PATRONAL DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_IGP DEFAULT (0),
    ISR DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_ISR DEFAULT (0),
    OTRAS_DEDUCCIONES DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_ODED DEFAULT (0),
    TOTAL_INGRESOS DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_TING DEFAULT (0),
    TOTAL_DEDUCCIONES DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_TDED DEFAULT (0),
    NETO_PAGAR DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_NETO DEFAULT (0),
    FECHA_ALTA DATE NULL,
    FECHA_BAJA DATE NULL,
    COD_CENTRO_TRABAJO VARCHAR(10) NULL,
    DEPARTAMENTO VARCHAR(120) NULL,
    CONDICION_LABORAL VARCHAR(1) NULL,
    TIPO_SALARIO_IGSS VARCHAR(2) NULL,
    TIEMPO_COMPLETO VARCHAR(2) NULL,
    COD_OCUPACION_IGSS VARCHAR(10) NULL,
    INCLUIDO VARCHAR(2) NOT NULL CONSTRAINT DF_NOMINA_DET_INC DEFAULT ('SI'),
    OBS VARCHAR(250) NULL,
    CONSTRAINT FK_NOMINA_DET_PLAN FOREIGN KEY (PLANILLA_ID) REFERENCES dbo.NOMINA_PLANILLAS (ID) ON DELETE CASCADE
  );
  CREATE INDEX IX_NOMINA_DET_PLAN ON dbo.NOMINA_DETALLE (PLANILLA_ID);
  CREATE INDEX IX_NOMINA_DET_EMP ON dbo.NOMINA_DETALLE (EMPNIT, CODEMPLEADO);
END;

-- Conceptos variables por línea (opcional, extensión)
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NOMINA_DETALLE_CONCEPTO' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  CREATE TABLE dbo.NOMINA_DETALLE_CONCEPTO (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    DETALLE_ID INT NOT NULL,
    CONCEPTO_ID INT NULL,
    CODIGO VARCHAR(20) NULL,
    DESCRIPCION VARCHAR(120) NULL,
    TIPO VARCHAR(3) NOT NULL,
    MONTO DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DCON_MONTO DEFAULT (0),
    CONSTRAINT FK_NOMINA_DCON_DET FOREIGN KEY (DETALLE_ID) REFERENCES dbo.NOMINA_DETALLE (ID) ON DELETE CASCADE
  );
  CREATE INDEX IX_NOMINA_DCON_DET ON dbo.NOMINA_DETALLE_CONCEPTO (DETALLE_ID);
END;

-- @UPDATER_CHUNK NOMINA_EMPLEADOS_CAMPOS
-- Campos adicionales en dbo.Empleados para nómina / IGSS
IF COL_LENGTH('dbo.Empleados', 'PRIMER_NOMBRE') IS NULL
  ALTER TABLE dbo.Empleados ADD PRIMER_NOMBRE VARCHAR(60) NULL;
IF COL_LENGTH('dbo.Empleados', 'SEGUNDO_NOMBRE') IS NULL
  ALTER TABLE dbo.Empleados ADD SEGUNDO_NOMBRE VARCHAR(60) NULL;
IF COL_LENGTH('dbo.Empleados', 'PRIMER_APELLIDO') IS NULL
  ALTER TABLE dbo.Empleados ADD PRIMER_APELLIDO VARCHAR(60) NULL;
IF COL_LENGTH('dbo.Empleados', 'SEGUNDO_APELLIDO') IS NULL
  ALTER TABLE dbo.Empleados ADD SEGUNDO_APELLIDO VARCHAR(60) NULL;
IF COL_LENGTH('dbo.Empleados', 'APELLIDO_CASADA') IS NULL
  ALTER TABLE dbo.Empleados ADD APELLIDO_CASADA VARCHAR(60) NULL;
IF COL_LENGTH('dbo.Empleados', 'NIT') IS NULL
  ALTER TABLE dbo.Empleados ADD NIT VARCHAR(20) NULL;
IF COL_LENGTH('dbo.Empleados', 'FECHA_INICIO') IS NULL
  ALTER TABLE dbo.Empleados ADD FECHA_INICIO DATE NULL;
IF COL_LENGTH('dbo.Empleados', 'FECHA_NACIMIENTO') IS NULL
  ALTER TABLE dbo.Empleados ADD FECHA_NACIMIENTO DATE NULL;

-- Campos extras en empleados / detalle de nómina (instalaciones previas)
IF COL_LENGTH('dbo.NOMINA_EMPLEADO', 'DEPARTAMENTO') IS NULL
  ALTER TABLE dbo.NOMINA_EMPLEADO ADD DEPARTAMENTO VARCHAR(120) NULL;
IF COL_LENGTH('dbo.NOMINA_EMPLEADO', 'BONO_LEY') IS NULL
  ALTER TABLE dbo.NOMINA_EMPLEADO ADD BONO_LEY DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_EMP_BONO_LEY DEFAULT (0);
IF COL_LENGTH('dbo.NOMINA_EMPLEADO', 'BONO_ADICIONAL') IS NULL
  ALTER TABLE dbo.NOMINA_EMPLEADO ADD BONO_ADICIONAL DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_EMP_BONO_ADI DEFAULT (0);
IF COL_LENGTH('dbo.NOMINA_DETALLE', 'DEPARTAMENTO') IS NULL
  ALTER TABLE dbo.NOMINA_DETALLE ADD DEPARTAMENTO VARCHAR(120) NULL;
IF COL_LENGTH('dbo.NOMINA_DETALLE', 'BONO_LEY') IS NULL
  ALTER TABLE dbo.NOMINA_DETALLE ADD BONO_LEY DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_BONO_LEY DEFAULT (0);
IF COL_LENGTH('dbo.NOMINA_DETALLE', 'BONO_ADICIONAL') IS NULL
  ALTER TABLE dbo.NOMINA_DETALLE ADD BONO_ADICIONAL DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_BONO_ADI DEFAULT (0);
