-- Vales a empleados: CODCAJA nullable (ya no van al corte de caja) + CUOTAS.
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NOMINA_VALES_EMPLEADOS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  IF EXISTS (
    SELECT 1
    FROM sys.columns
    WHERE object_id = OBJECT_ID('dbo.NOMINA_VALES_EMPLEADOS')
      AND name = 'CODCAJA'
      AND is_nullable = 0
  )
    ALTER TABLE dbo.NOMINA_VALES_EMPLEADOS ALTER COLUMN CODCAJA INT NULL;

  IF COL_LENGTH('dbo.NOMINA_VALES_EMPLEADOS', 'CUOTAS') IS NULL
    ALTER TABLE dbo.NOMINA_VALES_EMPLEADOS ADD CUOTAS INT NOT NULL CONSTRAINT DF_NOMINA_VALES_CUOTAS DEFAULT (1);
END;
GO
